[package]
name = "git-pick"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
git2 = { version = "0.18", features = ["vendored-libgit2", "vendored-openssl"] }
tempfile = "3.10"
thiserror = "1.0"
walkdir = "2.5"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.1"
